language: rust
sudo: false

env:
  global:
    - secure: HtdcoBljsPpR2xPwlgKLzWWADjV30KrqD7Zc2gnDbAcbdfwGZ67z4ykpACKYjKJyYIjAkA4LxrzKghIH6bugg+qYDtUb74tG/QUSFKFbexM2PtmV6YDP4k7bfda3p1qrjL/JmmUeP3g6WZFHVjMHKtks1cb05vY4tIM7kyfayNE=

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - cargo package --verbose

deploy:
  provider: releases
  api-key:
    secure: g3+keH6uHwJdJyoqNUokW+ydRyJHpy5s/a0tUFFK6zDXL92srhRQt4bzn0zBAH+Upi9GtWhiXmbhlUJx7pfRzZuYxCEv/TyqS1e/F3l93BO+w3j397xfxUzHI+wjtmomWZz6hCiHWmy77w7VeOJ1Id/Xc9ZwSB1HtII/1F5T4Eo=
  file: target/package/roaring-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_deploy:
  - git fetch git://github.com/$TRAVIS_REPO_SLUG gh-pages
  - git checkout -b gh-pages FETCH_HEAD
  - mv target/doc docs/$TRAVIS_TAG
  - git add docs/$TRAVIS_TAG
  - git commit -m "Add API docs for $TRAVIS_TAG"
  - git push git://$GITHUB_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG gh-pages
