language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test

matrix:
  include:
  - name: clippy
    rust: stable
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy --lib --tests -- -D warnings

branches:
  only: [staging, trying, master]
