language: rust
sudo: false

env:
  global:
    - secure: aOiqRRhbGw+r7P1PleSNKk5JTkItW/tQBYBhxGdJ7gN9KvlBHEmBHNd5Yl8AuE5R9W27Eo/BgtXIu09EMuND8cLr92b1P1ru1ebQMM+2FburF1y4psZakecSWAMDlF+km/cdES/AzIJ7dI1Fc4dGE/zNMuLLYEKmSDtVMHXucaI=

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - cargo package --verbose

deploy:
  provider: releases
  api-key:
    secure: YUXdO4SZv3+Cm550DGc9WLYRWHaBC4LWYkJK2sbR+GjSkNSvKHfxOe0+pDzJGHNY+QOWKal37H6bCGmk43xHgwWExb0nZ+Vp1nJG/nUeTcglF4tYSX+GJQEOioj1YmaOai0NuJ1peDS8TZXYmbghMc4vnLUnYg7t4gQ3m8M/fVY=
  file: target/package/roaring-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_deploy:
  - git remote add github https://$GITHUB_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  - git fetch github gh-pages
  - git checkout -b gh-pages FETCH_HEAD
  - mv target/doc docs/$TRAVIS_TAG
  - git add docs/$TRAVIS_TAG
  - git commit -m "Add API docs for $TRAVIS_TAG"
  - git push github gh-pages:gh-pages
