[package]
name = "roaring"
version = "0.5.0"
authors = ["Wim Looman <wim@nemo157.com>"]
description = "http://roaringbitmap.org : A better compressed bitset - pure Rust implementation "

documentation = "https://nemo157.com/roaring-rs"
repository = "https://github.com/Nemo157/roaring-rs"

readme = "README.md"
keywords = ["roaring", "data-structure", "bitmap"]

license = "MIT/Apache-2.0"

[dependencies]
byteorder = "0.5.3"
