[package]

name = "roaring"
version = "0.4.0"
authors = ["Wim Looman <wim@nemo157.com>"]
description = "http://roaringbitmap.org for http://www.rust-lang.org"

documentation = "https://nemo157.com/roaring-rs"
homepage = "https://nemo157.com/roaring-rs"
repository = "https://github.com/Nemo157/roaring-rs"

readme = "README.md"
keywords = ["roaring", "data-structure", "bitmap"]

license = "MIT/Apache-2.0"

[dependencies]
num = "*"
